import { Memberships } from '../../models/products';

export const OGTags = [
  {
    type: '0',
    label: 'Autogenerated',
  },
  {
    type: '1',
    label: 'Custom',
  },
];

export const metaDesc = [
  {
    type: 'A',
    label: 'Autogenerated',
  },
  {
    type: 'C',
    label: 'Custom',
  },
];

export const memberships: Memberships[] = [
  {
    label: 'General ',
    value: 4,
  },
];
export const sale_unit = [{ value: '$' }, { value: '%' }];

export const searchIn = [
  {
    value: 'name',
    title: 'Name',
  },
  {
    value: 'sku',
    title: 'SKU',
  },
  {
    value: 'description',
    title: 'Full Description',
  },
];

export const tableHeaderLabel = [
  {
    name: 'SKU',
    canSort: true,
  },
  {
    name: 'Name',
    canSort: true,
  },
  {
    name: 'Category',
    canSort: false,
  },
  {
    name: 'Price',
    canSort: true,
  },
  {
    name: 'In stock',
    canSort: true,
  },
  {
    name: 'Vendor',
    canSort: true,
  },
  {
    name: 'Arrival Date',
    canSort: true,
  },
];

export const stockStatus = [
  {
    value: 'all',
    name: 'Any stock status',
  },
  {
    value: 'in',
    name: 'In stock',
  },
  {
    value: 'low',
    name: 'Low stock',
  },
  {
    value: 'out',
    name: 'SOLD',
  },
];

export const availability = [
  { value: 'all', name: 'Any availability status' },
  { value: '1', name: 'Only enabled' },
  { value: '0', name: 'Only disabled' },
];
